// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Tentativa de carregar variáveis de ambiente
const supabaseUrl = import.meta.env.NEXT_PUBLIC_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug: Log das variáveis de ambiente
console.log('🔍 DEBUG - Variáveis de ambiente:');
console.log('NEXT_PUBLIC_SUPABASE_URL:', import.meta.env.NEXT_PUBLIC_SUPABASE_URL);
console.log('VITE_SUPABASE_URL:', import.meta.env.VITE_SUPABASE_URL);
console.log('NEXT_PUBLIC_SUPABASE_ANON_KEY:', import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ? 'EXISTS' : 'MISSING');
console.log('VITE_SUPABASE_ANON_KEY:', import.meta.env.VITE_SUPABASE_ANON_KEY ? 'EXISTS' : 'MISSING');
console.log('supabaseUrl:', supabaseUrl);
console.log('supabaseAnonKey:', supabaseAnonKey ? 'EXISTS' : 'MISSING');

// Se as variáveis não estiverem disponíveis, usar valores hardcoded temporariamente
const finalSupabaseUrl = supabaseUrl || 'https://geojqrpzcyiyhjzobggy.supabase.co';
const finalSupabaseAnonKey = supabaseAnonKey || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdlb2pxcnB6Y3lpeWhqem9iZ2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Nzg2MjksImV4cCI6MjA2OTU1NDYyOX0.GOYSjVMwIIrmCaTWc6lXUadCyIclaMYeqRrwapiFWg8';

if (!finalSupabaseUrl || !finalSupabaseAnonKey) {
  console.error('❌ ERRO: Variáveis de ambiente não encontradas!');
  console.error('supabaseUrl:', supabaseUrl);
  console.error('supabaseAnonKey:', supabaseAnonKey);
  throw new Error('Missing Supabase environment variables. Please check your .env file.');
}

console.log('✅ Usando configuração Supabase:', finalSupabaseUrl ? 'URL OK' : 'URL MISSING', finalSupabaseAnonKey ? 'KEY OK' : 'KEY MISSING');

export const supabase = createClient(finalSupabaseUrl, finalSupabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Debug: Verificar configuração do cliente
console.log('🔍 DEBUG - Cliente Supabase configurado:', {
  url: finalSupabaseUrl,
  hasKey: !!finalSupabaseAnonKey,
  isLocalhost: window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1',
  currentUrl: window.location.href
});