// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geojqrpzcyiyhjzobggy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdlb2pxcnB6Y3lpeWhqem9iZ2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Nzg2MjksImV4cCI6MjA2OTU1NDYyOX0.GOYSjVMwIIrmCaTWc6lXUadCyIclaMYeqRrwapiFWg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});